#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_ip:
    path: /ip
    controller: App\Controller\DnsController::getIp

update_dns:
    path: /update
    controller: App\Controller\DnsController::update
